tortairWebsite/tortairWebsite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf.urls import url
from users import views as user_view

urlpatterns = [
    path('',include('webapp.urls')),
    path('register/',user_view.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name = 'users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name = 'users/logout.html'),name='logout'),
    path('admin/',admin.site.urls),

    url(r'^password_reset/$', auth_views.PasswordResetView.\
        as_view(template_name = 'registration/password_reset_form.html'), name='password_reset'),

    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.\
        as_view(template_name = 'registration/password_reset_done.html'), name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.\
        as_view(template_name = 'registration/password_reset_confirm.html'), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.\
        as_view(template_name = 'registration/password_reset_complete.html'), name='password_reset_complete'),
]

tortairWebsite/webapp/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'myapp'
urlpatterns = [
    #test link pages**********************************
    path('',views.index, name = 'index'),
    path('borrow', views.borrow, name='borrow'),
    path('new_equipment/', views.new_Equipment, name='new'),
    path('insert_borrow/', views.insert_borrow, name='insert_borrow'),
    path('borrow/<int:equipment_id>/detail', views.detail, name='detail'),
    path('ScanQrcode_borrow', views.ScanQrcode_borrow, name='ScanQrcode_borrow'),
    path('ScanQrcode_send', views.ScanQrcode_send, name='ScanQrcode_send'),
    url(r'Allow', views.Allow, name='Allow'),
    url(r'Update_Status_borrow', views.Update_Status_borrow, name='Update_Status_borrow'),
    url(r'Update_Status_send', views.Update_Status_send, name='Update_Status_send'),
    url(r'send_borrow', views.send_borrow, name='send_borrow'),
    url(r'Check_lass_than_date',views.Check_lass_than_date ,name='Check_lass_than_date'),
    url(r'Getname_list',views.Getname_list ,name='Getname_list'),
    url(r'borrow/(?P<username>\w+)/$',views.borrow_loing ,name='borrow_loing'),
    url(r'(?P<username>\w+)/Update_amount/$',views.Update_amount ,name='Update_amount'),
    url(r'(?P<username>\w+)/delete/$',views.Delete ,name='Delete'),
    url(r'Borrow_order/(?P<username>\w+)/$',views.Borrow_order ,name='Borrow_order'),
    url(r'Insert_borrow_order',views.Insert_borrow_order ,name='Insert_borrow_order'),
    url(r'Announce/$',views.Announce ,name='Announce'),
    url(r'Announce_all/$',views.Feth_announce ,name='Feth_announce'),
    #path('calendar/', views.calendar, name='calendar'),
    #*************************************************
] 

tortairWebsite/webapp/models.py
import datetime
from django.db import models
from django.utils import timezone
from datetime import datetime, timedelta
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.contrib.auth.models import User

class Test(models.Model):
    name = models.CharField(max_length=200)
    age = models.CharField(max_length=200)
    email = models.CharField(max_length=200)

    def __str__(self):
        return "%s %s %s" % (self.name, self.age, self.email)


class Table_equipment(models.Model):
    Eqm_name = models.CharField(max_length=200)
    Eqm_model = models.CharField(max_length=100)
    Amount = models.IntegerField(default=0)
    Date_add = models.DateField('date published')

    def __str__(self):
        return "%s %s %s" % (self.Eqm_name, self.Eqm_model, self.Amount)

    def was_published_recently(self):
        return self.Date_add >= timezone.now() - datetime.timedelta(days=1)

class Equipment_detail(models.Model):
    Eqm_ID = models.ForeignKey(Table_equipment, on_delete=models.CASCADE, null=True, blank=True)
    Detail = models.TextField()
    Img = ProcessedImageField(upload_to='Eqm_images/',
                                           processors=[ResizeToFill(650, 650)],
                                           format='JPEG',
                                           options={'quality': 60})
    def __str__(self):
        return "%s %s %s" % (self.Detail, self.Img, self.Eqm_ID)

class Borrow(models.Model):
    #users = models.ForeignKey(User,to_field='username',on_delete=models.CASCADE,null=True,default = None)

    First_name = models.CharField(max_length=100,null=True) 
    Last_name = models.CharField(max_length=100,null=True) 
    #Get_username = models.CharField(max_length=100,null=True)
    Get_eqm_id = models.IntegerField(default=0)
    Eqm_name = models.CharField(max_length=200,null=True) 
    Get_Amount = models.IntegerField(default=0)
    Br_code = models.CharField(max_length=100,null=True)
    date_br = models.DateField('date published',default = datetime.now().date())
    Date_repatriate = models.DateField('date published')
    Status_borrow = models.BooleanField(default=0)
    Status_repatriate = models.BooleanField(default=0)


class Borro_order(models.Model):
    users = models.ForeignKey(User,to_field='username',on_delete=models.CASCADE,null=True,default = None)
    Eqm_name = models.ForeignKey(Table_equipment,to_field='id',on_delete=models.CASCADE,null=True,default = None)
    Get_Amount = models.IntegerField(default=0)
    date_br = models.DateField('date published',default = datetime.now().date())
    Date_repatriate = models.DateField('date published')
class News(models.Model):
    head = models.CharField(max_length=200)
    body = models.TextField(max_length=500)
    
'''
class User(models.Model):
    Name = models.CharField(max_length=130)
    Email = models.EmailField(blank=True)
    Username = models.CharField(max_length = 60)
    Password = models.CharField(max_length = 60)
    date_regis = models.DateField(("Date"), default=datetime.date.today)
'''

tortairWebsite/webapp/forms.py
from django import forms
from .models import Borro_order


    











































'''
class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'password_mismatch': ("The two password fields didn't match."),
    }
    password1 = forms.CharField(label=("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(label=("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=("Enter the same password as above, for verification."))
    Email = forms.EmailField()
    class Meta:
        model = User
        fields = ("Name","Email","Username")

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user
'''

tortairWebsite/webapp/views.py
from django.http import HttpResponse, HttpResponseRedirect,HttpResponseForbidden
from django.http import Http404
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required


from django.http import JsonResponse
from django.core import serializers
import json


from datetime import datetime, timedelta

from webapp.models import Table_equipment
from webapp.models import Equipment_detail
from webapp.models import Borrow
from webapp.models import Borro_order
from webapp.models import News

from django.contrib.auth.models import User
from django.utils.crypto import get_random_string as Ran_str
from django.contrib.sessions.backends.db import SessionStore 
from django.contrib import sessions
import random
import qrcode

from webapp.scanqrcode import Borrow_code as br_code
from PIL import Image , ImageDraw

s = SessionStore()
s['check_insert']=''
# link pages*******************************

def index(request):
    return render(request, 'webapp/index.html',{'page_index':1})

def borrow(request):
    s['check'] = 'empty'
    s['scan'] = 'empty'
    s['check_insert'] = ''
    data = Equipment_detail.objects.all()
    if 'search' in request.GET:
        data = ''
        search = request.GET['search']
        data = Equipment_detail.objects.filter(Eqm_ID__Eqm_name__icontains = search)\
             | Equipment_detail.objects.filter(Eqm_ID__Eqm_model__icontains = search)
    request.session[0] = ''
    paginator = Paginator(data, 12)
    num_page = paginator.page_range
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    
    return render(request, 'webapp/contents/fetch.html',{   'data': contacts,
                                                            'num_page':num_page,
                                                        })

@login_required()
def borrow_loing(request,username):
    s['check'] = 'empty'
    s['scan'] = 'empty'
    s['check_insert'] = ''
    data = Equipment_detail.objects.all()
    if 'search' in request.GET:
        data = ''
        search = request.GET['search']
        data = Equipment_detail.objects.filter(Eqm_ID__Eqm_name__icontains = search)\
             | Equipment_detail.objects.filter(Eqm_ID__Eqm_model__icontains = search)
    request.session[0] = ''
    paginator = Paginator(data, 12)
    num_page = paginator.page_range
    page = request.GET.get('page')
    contacts = paginator.get_page(page)

    #**********************************
    datas = Borro_order.objects.filter(users = username)
    amount = len(datas)  
    #**********************************
    
    return render(request, 'webapp/contents/fetch.html',{   'data': contacts,
                                                            'num_page':num_page,
                                                            'Amount':amount,
                                                            'pageCheck':'check_1'})

def new_Equipment(request):
    s['check_insert'] = ''
    data = Equipment_detail.objects.all().order_by('-id')[:10]
    news_f = News.objects.all().order_by('-id')[:3]
    return render(request, 'webapp/contents/new_equipment.html',{'data': data,'news_f':news_f})

@login_required()
def Insert_borrow_order(request):
    if request.method == 'POST':
        data = Borro_order.objects.create(
            users = User.objects.get( username = request.POST['username'] ),
            Eqm_name = Table_equipment.objects.get(id = request.POST['ID']),
            Get_Amount = request.POST['Amount'],
            Date_repatriate = request.POST['dates'],
        )
        if s['check'] == 'empty':
            data.save()
        s['check'] = 'not empty'

        #**********************************
        datas = Borro_order.objects.filter(users = request.POST['username'])
        amount = len(datas)  
        #**********************************

    return render(request,'webapp/contents/orderlist.html',{'datas': datas,'Amount':amount,'pageCheck':'check_1'})
    
@login_required()
def Borrow_order(request,username):

    #**********************************
    data = Borro_order.objects.filter(users = username)
    amount = len(data)
    #********************************** 
    
    if amount == 0:
        massage = 'ไม่มีรายการอุปกรณ์ที่ยืม'
        return render(request,'webapp/contents/orderlist.html',{'datas': data,'Amount':amount,'pageCheck':'check_1','massage': massage})  
    else:
        return render(request,'webapp/contents/orderlist.html',{'datas': data,'Amount':amount,'pageCheck':'check_1'})


@login_required()
def insert_borrow(request):
    if request.method == 'POST':
        datass = Borro_order.objects.filter(users = request.POST['username'])

        '''--------ramdom Borrow Code--------'''
        br_code = borrowCode() 
        if not datass:

            #**********************************
            amount = len(datass)  
            #*********************************  

            return render(request,'webapp/contents/orderlist.html',{'datas': datass,'Amount':amount,'pageCheck':'check_1','massage':'ไม่มีรายการอุปกรณ์ที่ยืม'})
        else:
            for data in datass:
                '''-------ลบจากจำนวนที่ยืม-------'''
                Eqm = Table_equipment.objects.get(id = data.Eqm_name.id)
                Amount = data.Get_Amount
                Amounts = Eqm.Amount - Amount

                value = Borrow( First_name = data.users.first_name ,Last_name = data.users.last_name,
                            Eqm_name = data.Eqm_name,Get_Amount = Amount,
                            Br_code = br_code, Date_repatriate =data.Date_repatriate,
                            Get_eqm_id = data.Eqm_name.id,date_br = data.date_br)
                Eqm.Amount = Amounts
                value.save()
                Eqm.save()

            datass.delete()
            img = qrcode.make(br_code)
            draw = ImageDraw.Draw(img)
            draw.text((125,260),text = br_code)
            img.save('webapp/static/include/Qrcode/borrowQR.jpg')
            
            s['Check_username'] = ''

            return render(request, 'webapp/showQrcode.html')


@login_required()
def Allow(request):
    s['scan'] = 'empty'
    s['check_insert'] = ''
    data =  Borrow.objects.filter(Status_borrow = 0)\
            & Borrow.objects.filter(Status_repatriate = 0 )
    if 'search2' in request.GET:
        data = ''
        search = request.GET['search2']
        data =  (Borrow.objects.filter(Br_code__icontains = search)\
                | Borrow.objects.filter(First_name__icontains = search))\
                & Borrow.objects.filter(Status_borrow = 0 )\
                & Borrow.objects.filter(Status_repatriate = 0 )
                
    return render(request, 'webapp/contents/admin.html',{'datas':data,'check_page':1})

@login_required()
def send_borrow(request):
    s['scan'] = 'empty'
    data =  Borrow.objects.filter(Status_borrow = 1)\
            & Borrow.objects.filter(Status_repatriate = 0 )\
            & Borrow.objects.filter(Date_repatriate__gte = datetime.now().date())
    if 'search3' in request.GET:
        data = ''
        search = request.GET['search3']
        data =  (Borrow.objects.filter(Br_code__icontains = search)\
                | Borrow.objects.filter(First_name__icontains = search))\
                & Borrow.objects.filter(Status_borrow = 1)\
                & Borrow.objects.filter(Status_repatriate = 0 )\
                & Borrow.objects.filter(Date_repatriate__gte = datetime.now().date())
    return render(request, 'webapp/contents/admin.html',{'datas':data,'check_page':2})

    
@login_required()
def ScanQrcode_borrow(request):
    data =''
    if s['scan'] == 'empty':
        br_c = br_code()
        if br_c != '0':
            s['get_br_c'] = br_c
            s['scan'] = 'not empty'
            data =  Borrow.objects.filter(Br_code__icontains = s['get_br_c'])\
                    & Borrow.objects.filter(Status_borrow = 0)\
                    & Borrow.objects.filter(Status_repatriate = 0 )
            return render(request, 'webapp/contents/admin.html',{'datas':data,'check':1})
        else:
            s['get_br_c'] = br_c
            return render(request, 'webapp/contents/admin.html',{'datas':data,'check':1})
    else:
        data =  Borrow.objects.filter(Br_code__icontains = s['get_br_c'])\
                & Borrow.objects.filter(Status_borrow = 0)\
                & Borrow.objects.filter(Status_repatriate = 0 )
        return render(request, 'webapp/contents/admin.html',{'datas':data,'check':1})
        
@login_required()
def ScanQrcode_send(request):
    data =''
    if s['scan'] == 'empty':
        br_c = br_code()

        #*******************check page number chang color button************************
        check_date = Borrow.objects.filter(Date_repatriate__lte = datetime.now().date()-timedelta(days=1))\
                     & Borrow.objects.filter(Br_code__icontains = br_c)

        if not check_date:
            check_page = 2
        else:
            check_page = 3
        #********************************************************************************

        if br_c != '0':
            s['get_br_c'] = br_c
            s['scan'] = 'not empty'
            data =  Borrow.objects.filter(Br_code__icontains = s['get_br_c'])\
                    & Borrow.objects.filter(Status_borrow = 1)\
                    & Borrow.objects.filter(Status_repatriate = 0 )
            return render(request, 'webapp/contents/admin.html',{'datas':data,'check':1,'check_page':check_page})
        else:
            s['get_br_c'] = br_c
            return render(request, 'webapp/contents/admin.html',{'datas':data,'check':1,'check_page':check_page})
    else:
        data =  Borrow.objects.filter(Br_code__icontains = s['get_br_c'])\
                & Borrow.objects.filter(Status_borrow = 1)\

tortairWebsite/webapp/templates/webapp/include/footer.html
<footer>
  <div class="mt-5 pt-5 pb-5 footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-5 col-xs-12 about-company">
          <p class="pr-5 text-white-50">มหาวิทยาลัยเกษตรศาสตร์ วิทยาเขตเฉลิมพระเกียรติ จังหวัดสกลนคร</p>
          <p class="pr-5 text-white-50">ระบบยืมคืนอุปกรณ์</p>
          <p class="pr-5 text-white-50">ติดต่่อ : &nbsp;<a href="javascript:void(0)"><i
                class="fab fa-facebook mr-1"></i></a><a href="javascript:void(0)"><i class="fab fa-line"></i></a></p>
        </div>
        <div class="col-lg-3 col-xs-12 links">
          <h4 class="mt-lg-0 mt-sm-3">ลิ้งอื่นๆ</h4>
          <ul class="m-0 p-0">
            <li>- <a href="javascript:void(0)">เว็บมหาลัย</a></li>
            <li>- <a href="javascript:void(0)">ระบบสารสนเทศ</a></li>
          </ul>
        </div>
        <div class="col-lg-4 col-xs-12 location">
          <h4 class="mt-lg-0 mt-sm-4">ที่ตั้ง</h4>
          <p>59 หมู่ 1 ตำบลเชียงเครือ อำเภอเมืองสกลนคร สกลนคร 47000</p>
          <p class="mb-0"><i class="fa fa-phone mr-3"></i>061-0287788</p>
          <p><i class="fa fa-envelope-o mr-3"></i>tongtangvi@gmail.com</p>
        </div>
      </div>
      <div class="row mt-5">
        <div class="col copyright">
          <p class=""><small class="text-white-50">&copy; tongtangvi@gmail.com | Design by Atsada karanet</small></p>
        </div>
      </div>
    </div>
  </div>
</footer>

tortairWebsite/webapp/templates/webapp/include/header.html
<header class="fixed-top"> <!--fixed-top-->
    <div class="container ">
        <nav>
            <h1 class="brand"> <a href="{% url 'myapp:index' %}">Equi<span>p</span>ment</a></h1>
            <ul>
                <li><a href="{% url 'myapp:new' %}">อุปกรณ์มาใหม่</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'myapp:borrow_loing' user.username %}">ยืมอุปกรณ์</a></li>
                    {% if  user.is_staff == True%}
                        <li><a href="{% url 'myapp:Allow' %}">Admin</a></li>
                    {% endif %}
                    {% if pageCheck == 'check_1' %}
                        <li><a href="{% url 'myapp:Borrow_order' user.username %}">รายการที่จะยืม<span style = "background-color: red;" class="badge">{{Amount}}</a></li>
                    {% endif %}

                <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'myapp:borrow'%}">ยืมอุปกรณ์</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="{% url 'register' %}">Register</a></li>
                {% endif %}
                <li><a href="javasript:void(0)" id = "contract_clk" >ติดต่อ</a></li>
            </ul>
        </nav>
    </div>
</header>
{% if page_index != 1 %}
<div class="modal fade" id="exampleModal_1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">ติดต่อ</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="#" method="post" id ="auto_form1">{% csrf_token %}
           <div class="form-group">
              <label for="exampleInputEmail1">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
              <small id="emailHelp" class="form-text text-muted">กรุณากรอก Email ให้ถูก</small>
            </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">ข้อความ:</label>
            <textarea class="form-control" id="message-text" name = "message"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-success submit_s1 ">Send</button>
      </div>
    </div>
  </div>
</div>
<script>
    $('#contract_clk').on('click',function(){
        $('#exampleModal_1').modal('show')
    })
    $( ".submit_s1" ).on('click',function(){
        $("#auto_form1").submit();
    });
</script>
{% endif %}

tortairWebsite/webapp/templates/webapp/include/importCSS.html
{% load static from staticfiles %}
<link rel="stylesheet" href="{% static 'include/bootstrap/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'include/bootstrap/jquery.datetimepicker.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'include/font/font.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'include/css/borrow.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'include/css/header.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'include/css/footer.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'include/css/new.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'include/css/admin.css' %}">

tortairWebsite/webapp/templates/webapp/include/importJS.html
{% load static %}
{#<script src="{% static 'include/js_libary/jquery-3.3.1.slim.min.js' %}"></script>#}
<script src="{% static 'include/js_libary/jquery-3.4.1.min.js' %}"></script> 
<script src="{% static 'include/js_libary/jquery.datetimepicker.full.js' %}" ></script>  
<script src="{% static 'include/js_libary/bootstrap.min.js' %}" ></script>  
<script src="{% static 'include/js_libary/popper.min.js' %}"></script> 
<script src="{% static 'include/js_libary/a55f9ec08c.js' %}"></script>  

tortairWebsite/webapp/templates/webapp/include/nav_admin.html
<nav2 class="navbar navbar-expand-lg">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if  user.is_staff == True %}
                <li class="nav-item ">
                     <p>&nbsp;&nbsp;<a href = "{% url 'myapp:Allow' %}">รออนุมัติ</a></p>
                </li>
                <li class="nav-item ">
                     <p>&nbsp;&nbsp;<a href = "{% url 'myapp:send_borrow' %}">อนุมัติแล้ว/รอคืน</a></p>
                </li>
                <li class="nav-item ">
                     <p>&nbsp;&nbsp;<a href = "{% url 'myapp:Check_lass_than_date' %}">เลยกำหนดส่งคืน</a></p>
                </li>
                <li class="nav-item ">
                     <p>&nbsp;&nbsp;<a href = "{% url 'myapp:Getname_list' %}">คืนอุปกรณ์แล้ว</a></p>
                </li>
                 <li class="nav-item ">
                     <p>&nbsp;&nbsp;<a href = "{% url 'admin:index' %}">จัดการข้อมูล</a></p>
                </li>
                <li class="nav-item ">
                     <p>&nbsp;&nbsp;<a id = "click_alert" href = "javascript:void(0)">ประกาศ</a></p>
                </li>
             {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
        {% if  check_page != 4%}
            <input class="form-control mr-sm-2" 
            type="search" 
            placeholder="Search" 
            aria-label="Search"
        {% if check_page == 3 %}
            name = "search4"
        {% elif check_page == 2 %}
            name = "search3"
        {% else %}
            name = "search2"
        {% endif %}
            >
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        {% endif %}
        </form>

    </div>
      
<div class="modal fade" id="exampleModal_3" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">ประกาศ</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'myapp:Announce' %}" method="post" id ="auto_form2">{% csrf_token %}
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">หัวข้อ:</label>
            <input type="text" class="form-control" id="recipient-name" name = "head">
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">ข้อความ:</label>
            <textarea class="form-control" id="message-text" name = "body"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-success submit_s ">Send</button>
      </div>
    </div>
  </div>
</div>

<script>
  $('#click_alert').on('click',function(){
      $('#exampleModal_3').modal('show')
  })
  $(".submit_s" ).on('click',function(){
      $("#auto_form2").submit();
  });
</script>  
</nav2>

tortairWebsite/webapp/templates/webapp/include/navberborrow.html
{% if detail.Eqm_ID.Eqm_name|length > 0%}
{% else %}
<nav2 class="navbar navbar-expand-lg">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated%}
                <i class="fas fa-user mt-1" style = "color:white"></i>
                <li class="nav-item">
                    <p>&nbsp;{{user.username}}</p>
                </li>
            {% endif %}
            <li class="nav-item">
            {% if user.is_staff != True and user.is_authenticated %}
                <p>&nbsp;คุณ: {{user.first_name}}</p>
             {% elif user.is_staff == True%}
                <p>&nbsp;Admin: {{user.first_name}}</p>
             {% endif %}
              </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" 
            type="search" 
            placeholder="Search" 
            aria-label="Search"
            name = "search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav2>
{% endif %}