tortairWebsite/tortairWebsite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf.urls import url
from users import views as user_view

urlpatterns = [
    path('',include('webapp.urls')),
    path('register/',user_view.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name = 'users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name = 'users/logout.html'),name='logout'),
    path('admin/',admin.site.urls),

    url(r'^password_reset/$', auth_views.PasswordResetView.\
        as_view(template_name = 'registration/password_reset_form.html'), name='password_reset'),

    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.\
        as_view(template_name = 'registration/password_reset_done.html'), name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.\
        as_view(template_name = 'registration/password_reset_confirm.html'), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.\
        as_view(template_name = 'registration/password_reset_complete.html'), name='password_reset_complete'),
]

tortairWebsite/webapp/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'myapp'
urlpatterns = [
    #test link pages**********************************
    path('',views.index, name = 'index'),
    path('borrow', views.borrow, name='borrow'),
    path('new_equipment/', views.new_Equipment, name='new'),
    path('insert_borrow/', views.insert_borrow, name='insert_borrow'),
    path('borrow/<int:equipment_id>/detail', views.detail, name='detail'),
    path('ScanQrcode_borrow', views.ScanQrcode_borrow, name='ScanQrcode_borrow'),
    path('ScanQrcode_send', views.ScanQrcode_send, name='ScanQrcode_send'),
    url(r'Allow', views.Allow, name='Allow'),
    url(r'Update_Status_borrow', views.Update_Status_borrow, name='Update_Status_borrow'),
    url(r'Update_Status_send', views.Update_Status_send, name='Update_Status_send'),
    url(r'send_borrow', views.send_borrow, name='send_borrow'),
    url(r'Check_lass_than_date',views.Check_lass_than_date ,name='Check_lass_than_date'),
    url(r'Getname_list',views.Getname_list ,name='Getname_list'),
    url(r'borrow/(?P<username>\w+)/$',views.borrow_loing ,name='borrow_loing'),
    url(r'(?P<username>\w+)/Update_amount/$',views.Update_amount ,name='Update_amount'),
    url(r'(?P<username>\w+)/delete/$',views.Delete ,name='Delete'),
    url(r'Borrow_order/(?P<username>\w+)/$',views.Borrow_order ,name='Borrow_order'),
    url(r'Insert_borrow_order',views.Insert_borrow_order ,name='Insert_borrow_order'),
    url(r'Announce/$',views.Announce ,name='Announce'),
    url(r'Announce_all/$',views.Feth_announce ,name='Feth_announce'),
    #path('calendar/', views.calendar, name='calendar'),
    #*************************************************
] 

tortairWebsite/webapp/models.py
import datetime
from django.db import models
from django.utils import timezone
from datetime import datetime, timedelta
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.contrib.auth.models import User

class Test(models.Model):
    name = models.CharField(max_length=200)
    age = models.CharField(max_length=200)
    email = models.CharField(max_length=200)

    def __str__(self):
        return "%s %s %s" % (self.name, self.age, self.email)


class Table_equipment(models.Model):
    Eqm_name = models.CharField(max_length=200)
    Eqm_model = models.CharField(max_length=100)
    Amount = models.IntegerField(default=0)
    Date_add = models.DateField('date published')

    def __str__(self):
        return "%s %s %s" % (self.Eqm_name, self.Eqm_model, self.Amount)

    def was_published_recently(self):
        return self.Date_add >= timezone.now() - datetime.timedelta(days=1)

class Equipment_detail(models.Model):
    Eqm_ID = models.ForeignKey(Table_equipment, on_delete=models.CASCADE, null=True, blank=True)
    Detail = models.TextField()
    Img = ProcessedImageField(upload_to='Eqm_images/',
                                           processors=[ResizeToFill(650, 650)],
                                           format='JPEG',
                                           options={'quality': 60})
    def __str__(self):
        return "%s %s %s" % (self.Detail, self.Img, self.Eqm_ID)

class Borrow(models.Model):
    #users = models.ForeignKey(User,to_field='username',on_delete=models.CASCADE,null=True,default = None)

    First_name = models.CharField(max_length=100,null=True) 
    Last_name = models.CharField(max_length=100,null=True) 
    #Get_username = models.CharField(max_length=100,null=True)
    Get_eqm_id = models.IntegerField(default=0)
    Eqm_name = models.CharField(max_length=200,null=True) 
    Get_Amount = models.IntegerField(default=0)
    Br_code = models.CharField(max_length=100,null=True)
    date_br = models.DateField('date published',default = datetime.now().date())
    Date_repatriate = models.DateField('date published')
    Status_borrow = models.BooleanField(default=0)
    Status_repatriate = models.BooleanField(default=0)


class Borro_order(models.Model):
    users = models.ForeignKey(User,to_field='username',on_delete=models.CASCADE,null=True,default = None)
    Eqm_name = models.ForeignKey(Table_equipment,to_field='id',on_delete=models.CASCADE,null=True,default = None)
    Get_Amount = models.IntegerField(default=0)
    date_br = models.DateField('date published',default = datetime.now().date())
    Date_repatriate = models.DateField('date published')
class News(models.Model):
    head = models.CharField(max_length=200)
    body = models.TextField(max_length=500)
    
'''
class User(models.Model):
    Name = models.CharField(max_length=130)
    Email = models.EmailField(blank=True)
    Username = models.CharField(max_length = 60)
    Password = models.CharField(max_length = 60)
    date_regis = models.DateField(("Date"), default=datetime.date.today)
'''

tortairWebsite/webapp/forms.py
from django import forms
from .models import Borro_order


    











































'''
class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'password_mismatch': ("The two password fields didn't match."),
    }
    password1 = forms.CharField(label=("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(label=("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=("Enter the same password as above, for verification."))
    Email = forms.EmailField()
    class Meta:
        model = User
        fields = ("Name","Email","Username")

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user
'''

tortairWebsite/webapp/views.py
from django.http import HttpResponse, HttpResponseRedirect,HttpResponseForbidden
from django.http import Http404
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required


from django.http import JsonResponse
from django.core import serializers
import json


from datetime import datetime, timedelta

from webapp.models import Table_equipment
from webapp.models import Equipment_detail
from webapp.models import Borrow
from webapp.models import Borro_order
from webapp.models import News

from django.contrib.auth.models import User
from django.utils.crypto import get_random_string as Ran_str
from django.contrib.sessions.backends.db import SessionStore 
from django.contrib import sessions
import random
import qrcode

from webapp.scanqrcode import Borrow_code as br_code
from PIL import Image , ImageDraw

s = SessionStore()
s['check_insert']=''
# link pages*******************************

def index(request):
    return render(request, 'webapp/index.html',{'page_index':1})

def borrow(request):
    s['check'] = 'empty'
    s['scan'] = 'empty'
    s['check_insert'] = ''
    data = Equipment_detail.objects.all()
    if 'search' in request.GET:
        data = ''
        search = request.GET['search']
        data = Equipment_detail.objects.filter(Eqm_ID__Eqm_name__icontains = search)\
             | Equipment_detail.objects.filter(Eqm_ID__Eqm_model__icontains = search)
    request.session[0] = ''
    paginator = Paginator(data, 12)
    num_page = paginator.page_range
    page = request.GET.get('page')
    contacts = paginator.get_page(page)
    
    return render(request, 'webapp/contents/fetch.html',{   'data': contacts,
                                                            'num_page':num_page,
                                                        })

@login_required()
def borrow_loing(request,username):
    s['check'] = 'empty'
    s['scan'] = 'empty'
    s['check_insert'] = ''
    data = Equipment_detail.objects.all()
    if 'search' in request.GET:
        data = ''
        search = request.GET['search']
        data = Equipment_detail.objects.filter(Eqm_ID__Eqm_name__icontains = search)\
             | Equipment_detail.objects.filter(Eqm_ID__Eqm_model__icontains = search)
    request.session[0] = ''
    paginator = Paginator(data, 12)
    num_page = paginator.page_range
    page = request.GET.get('page')
    contacts = paginator.get_page(page)

    #**********************************
    datas = Borro_order.objects.filter(users = username)
    amount = len(datas)  
    #**********************************
    
    return render(request, 'webapp/contents/fetch.html',{   'data': contacts,
                                                            'num_page':num_page,
                                                            'Amount':amount,
                                                            'pageCheck':'check_1'})

def new_Equipment(request):
    s['check_insert'] = ''
    data = Equipment_detail.objects.all().order_by('-id')[:10]
    news_f = News.objects.all().order_by('-id')[:3]
    return render(request, 'webapp/contents/new_equipment.html',{'data': data,'news_f':news_f})

@login_required()
def Insert_borrow_order(request):
    if request.method == 'POST':
        data = Borro_order.objects.create(
            users = User.objects.get( username = request.POST['username'] ),
            Eqm_name = Table_equipment.objects.get(id = request.POST['ID']),
            Get_Amount = request.POST['Amount'],
            Date_repatriate = request.POST['dates'],
        )
        if s['check'] == 'empty':
            data.save()
        s['check'] = 'not empty'

        #**********************************
        datas = Borro_order.objects.filter(users = request.POST['username'])
        amount = len(datas)  
        #**********************************

    return render(request,'webapp/contents/orderlist.html',{'datas': datas,'Amount':amount,'pageCheck':'check_1'})
    
@login_required()
def Borrow_order(request,username):

    #**********************************
    data = Borro_order.objects.filter(users = username)
    amount = len(data)
    #********************************** 
    
    if amount == 0:
        massage = 'ไม่มีรายการอุปกรณ์ที่ยืม'
        return render(request,'webapp/contents/orderlist.html',{'datas': data,'Amount':amount,'pageCheck':'check_1','massage': massage})  
    else:
        return render(request,'webapp/contents/orderlist.html',{'datas': data,'Amount':amount,'pageCheck':'check_1'})


@login_required()
def insert_borrow(request):
    if request.method == 'POST':
        datass = Borro_order.objects.filter(users = request.POST['username'])

        '''--------ramdom Borrow Code--------'''
        br_code = borrowCode() 
        if not datass:

            #**********************************
            amount = len(datass)  
            #*********************************  

            return render(request,'webapp/contents/orderlist.html',{'datas': datass,'Amount':amount,'pageCheck':'check_1','massage':'ไม่มีรายการอุปกรณ์ที่ยืม'})
        else:
            for data in datass:
                '''-------ลบจากจำนวนที่ยืม-------'''
                Eqm = Table_equipment.objects.get(id = data.Eqm_name.id)
                Amount = data.Get_Amount
                Amounts = Eqm.Amount - Amount

                value = Borrow( First_name = data.users.first_name ,Last_name = data.users.last_name,
                            Eqm_name = data.Eqm_name,Get_Amount = Amount,
                            Br_code = br_code, Date_repatriate =data.Date_repatriate,
                            Get_eqm_id = data.Eqm_name.id,date_br = data.date_br)
                Eqm.Amount = Amounts
                value.save()
                Eqm.save()

            datass.delete()
            img = qrcode.make(br_code)
            draw = ImageDraw.Draw(img)
            draw.text((125,260),text = br_code)
            img.save('webapp/static/include/Qrcode/borrowQR.jpg')
            
            s['Check_username'] = ''

            return render(request, 'webapp/showQrcode.html')


@login_required()
def Allow(request):
    s['scan'] = 'empty'
    s['check_insert'] = ''
    data =  Borrow.objects.filter(Status_borrow = 0)\
            & Borrow.objects.filter(Status_repatriate = 0 )
    if 'search2' in request.GET:
        data = ''
        search = request.GET['search2']
        data =  (Borrow.objects.filter(Br_code__icontains = search)\
                | Borrow.objects.filter(First_name__icontains = search))\
                & Borrow.objects.filter(Status_borrow = 0 )\
                & Borrow.objects.filter(Status_repatriate = 0 )
                
    return render(request, 'webapp/contents/admin.html',{'datas':data,'check_page':1})

@login_required()
def send_borrow(request):
    s['scan'] = 'empty'
    data =  Borrow.objects.filter(Status_borrow = 1)\
            & Borrow.objects.filter(Status_repatriate = 0 )\
            & Borrow.objects.filter(Date_repatriate__gte = datetime.now().date())
    if 'search3' in request.GET:
        data = ''
        search = request.GET['search3']
        data =  (Borrow.objects.filter(Br_code__icontains = search)\
                | Borrow.objects.filter(First_name__icontains = search))\
                & Borrow.objects.filter(Status_borrow = 1)\
                & Borrow.objects.filter(Status_repatriate = 0 )\
                & Borrow.objects.filter(Date_repatriate__gte = datetime.now().date())
    return render(request, 'webapp/contents/admin.html',{'datas':data,'check_page':2})

    
@login_required()
def ScanQrcode_borrow(request):
    data =''
    if s['scan'] == 'empty':
        br_c = br_code()
        if br_c != '0':
            s['get_br_c'] = br_c
            s['scan'] = 'not empty'
            data =  Borrow.objects.filter(Br_code__icontains = s['get_br_c'])\
                    & Borrow.objects.filter(Status_borrow = 0)\
                    & Borrow.objects.filter(Status_repatriate = 0 )
            return render(request, 'webapp/contents/admin.html',{'datas':data,'check':1})
        else:
            s['get_br_c'] = br_c
            return render(request, 'webapp/contents/admin.html',{'datas':data,'check':1})
    else:
        data =  Borrow.objects.filter(Br_code__icontains = s['get_br_c'])\
                & Borrow.objects.filter(Status_borrow = 0)\
                & Borrow.objects.filter(Status_repatriate = 0 )
        return render(request, 'webapp/contents/admin.html',{'datas':data,'check':1})
        
@login_required()
def ScanQrcode_send(request):
    data =''
    if s['scan'] == 'empty':
        br_c = br_code()

        #*******************check page number chang color button************************
        check_date = Borrow.objects.filter(Date_repatriate__lte = datetime.now().date()-timedelta(days=1))\
                     & Borrow.objects.filter(Br_code__icontains = br_c)

        if not check_date:
            check_page = 2
        else:
            check_page = 3
        #********************************************************************************

        if br_c != '0':
            s['get_br_c'] = br_c
            s['scan'] = 'not empty'
            data =  Borrow.objects.filter(Br_code__icontains = s['get_br_c'])\
                    & Borrow.objects.filter(Status_borrow = 1)\
                    & Borrow.objects.filter(Status_repatriate = 0 )
            return render(request, 'webapp/contents/admin.html',{'datas':data,'check':1,'check_page':check_page})
        else:
            s['get_br_c'] = br_c
            return render(request, 'webapp/contents/admin.html',{'datas':data,'check':1,'check_page':check_page})
    else:
        data =  Borrow.objects.filter(Br_code__icontains = s['get_br_c'])\
                & Borrow.objects.filter(Status_borrow = 1)\

tortairWebsite/webapp/templates/webapp/contents/admin.html
{% extends 'webapp/base_admin.html' %}
{% block content %}

<div class = " container mt-5 st">
<br>

{% if check_page == 2 %}
    <h1 class = "head_h1">อนุมัติแล้ว/รอคืน</h1>
    <p><a href = "{% url 'myapp:ScanQrcode_send' %}"><i id = "qr"  class="fas fa-qrcode"></i></a>&nbsp;&nbsp;สแกนคิวอาร์โค้ด(Scan qrcode)</p>
{% elif  check_page == 1%}
    <h1 class = "head_h1">รอการอนุมัติ</h1>
    <p><a href = "{% url 'myapp:ScanQrcode_borrow' %}"><i id = "qr"  class="fas fa-qrcode"></i></a>&nbsp;&nbsp;สแกนคิวอาร์โค้ด(Scan qrcode)</p>
{% elif check_page == 3 %}
    <h1 class = "head_h1">เลยกำหนดส่งคืน</h1>
{% elif check_page == 4 %}
    <h1 class = "head_h1">คืนอุปกรณ์แล้ว</h1>
{% endif %}

<br>
{% if check == 1 %}
 <div class="modal fade bd-example-modal-lg Mymodel mt-5"  style = "font-family: 'Kanit', sans-serif;" >
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            {% if check_page == 2 %}
            <button type="button" class="btn btn-warning" onclick ="window.location.href='{% url 'myapp:send_borrow'%}'">กลับ</button>
            {% elif check_page == 3 %}
            <button type="button" class="btn btn-danger" onclick ="window.location.href='{% url 'myapp:send_borrow'%}'">กลับ</button>
            {% else %}
            <button type="button" class="btn btn-success" onclick ="window.location.href='{% url 'myapp:Allow'%}'">กลับ</button>
            {% endif %}
                <div style = "text-align:center">
                    {% endif %}
                    <table class="table table-hover table-light" id = "myTable">
                        <thead>
                                <tr>
                                <th scope="col">#</th>
                                <th scope="col">ชื่อ</th>
                                <th scope="col">นามสกุล</th>
                                <th scope="col">อุปกรณ์ที่ยืม</th>
                                <th scope="col">จำนวนที่ยืม/อัน</th>
                                <th scope="col">วันที่ยืม</th>
                                <th scope="col">วันที่คืน</th>
                                <th scope="col">รหัสคิวอาร์โค้ด</th>
                                {% if check_page == 3 or check_page == 2 or check_page == 1 %}
                                    <th scope="col">อนุมัติ</th>
                                {% endif %}
                                </tr>
                        </thead>
                        <tbody>
                             <script> 
                                 var i = 1
                             </script>
                            {% for data in datas %}
                                <tr>
                                <th scope="row">
                                    <script>
                                        document.write(i);
                                    </script>
                                </th>
                                <td>{{data.First_name}}</td>
                                <td>{{data.Last_name}}</td>
                                <td>{{data.Eqm_name}}</td>
                                <td>{{data.Get_Amount}}</td>
                                <td>{{data.date_br}}</td>
                                <td>{{data.Date_repatriate}}</td>
                                <td>{{data.Br_code}}</td>

                                {% if data.Status_borrow == 1 and data.Status_repatriate == 0 and check_page != 3 %}
                                    <td><button  id = "send{{data.id}}" type="button" class="btn btn-warning">คืนอุปกรณ์</button></td>
                                {% elif data.Status_borrow == 0 and data.Status_repatriate == 0 %}
                                    <td><button  id = "allow{{data.id}}" type="button" class="btn btn-success">อนุมัติ</button></td>
                                {% elif data.Status_borrow == 1 and data.Status_repatriate == 0 and check_page == 3 %}
                                    <td><button  id = "send{{data.id}}" type="button" class="btn btn-danger">คืนอุปกรณ์</button></td>
                                {% endif %}
                                
                                </tr>
                                
                                <script>

                                    i++;
                                    var token = '{{csrf_token}}';

                                    $('#allow{{data.id}}').on('click',function(event){
                                    $(this).closest ('tr').remove ();
                                    $.ajax({
                                            headers: { "X-CSRFToken": token },
                                            url: "Update_Status_borrow",
                                            type: "post",
                                            data: {'status': 1,'id':'{{data.id}}'},
                                            success:function(){
                                                   
                                                }
                                            });
                                        });

                                    $('#send{{data.id}}').on('click',function(event){
                                    $(this).closest ('tr').remove ();
                                    $.ajax({
                                            headers: { "X-CSRFToken": token },
                                            url: "Update_Status_send",
                                            type: "post",
                                            data: {'status': 1,'id':'{{data.id}}'},
                                            success:function(){
                                                   
                                                }
                                            });
                                        });
                                </script>
                            {% endfor %}
                        </tbody>
                     </table> 
{% if check == 1 %}
                </div>
            </div>
        </div>
    </div>
<br><br><br>
<br><br><br>
{% endif %}
</div>
{% endblock content %}

tortairWebsite/webapp/templates/webapp/contents/new_equipment.html
{% extends 'webapp/new.html' %}
{% load static %}
{% block content %}

 <div class="container margins">
  {% if messages %}
                {% for message in messages %}
                        <div class = "alert-{{message.tags}}">
                                {{message}}
                        </div>
                {% endfor %}
        {% endif %}
    <div class="row style_row">

      <div class="col-lg-2">
        <div class="navbar-nav style_s">
          <a href="{% url 'myapp:new' %}" class="list-group-item nounderline">อัพเดทล่าสุด</a>
          <a href="{% url 'myapp:Feth_announce' %}" class="list-group-item nounderline">ประกาศ</a>
        </div>
      </div>

      <!-- /.col-lg-3 -->
      <div class="col-lg-7 style_col">
      {% if page_news == 1 %}
          {% for vals in news_ss%}
             <div class="card mt-4">
              <div class="card-body">
                  <h4> {{vals.head}}</h4>
                  <p class="card-text">{{vals.body}}</p>
              </div>
              </div>
          {% endfor %}
      {% else %}
          {% for vals in data %}
            <div class="card mt-4">
                <img class="card-img-top img-fluid" src="{% static vals.Img.url %}"  style = "width:50%; margin:auto"alt="img">
                <div class="card-body">
                    <h3 class="card-title">{{vals.Eqm_ID.Eqm_name}}</h3>
                    <h4>จำนวน {{vals.Eqm_ID.Amount}}</h4>
                    <p class="card-text">{{vals.Detail|linebreaks}}</p>
                    <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
                    4.0 stars
                </div>
            </div>
          {% endfor %}
          
      {% endif %}
        
      </div>
      <!-- /.col-lg-9 -->
      <div class="col-lg-3">
          {% if page_news != 1 %}
            <div class = "card-body style_s">
                {% for news in news_f %}
                  <h4>{{news.head}}</h4>
                  <p>{{news.body}}</p>
                {% endfor %}
            </div>
          {% endif %}
         </div>
    </div>
  </div>
{% endblock content %}

tortairWebsite/webapp/templates/webapp/contents/orderlist.html
{% extends 'webapp/base_order.html' %}
{% block content %}

<style>
    .button3{
        color: white;
        border: none;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        background-color: #f44336;
        font-family: 'Kanit', sans-serif;
         
    }
    .button2{
        color: white;
        border: none;
        padding: 5px 15px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        background-color: #f44336;
        font-family: 'Kanit', sans-serif;
         
    }
    .style_231{
        width:10%;
    }
    h2{
        font-family: 'Kanit', sans-serif;
    }
</style>
   
    <div class = " container st2">
        {% if massege != '' %}
            {% if check_s == 1 %}
             <div class="alert alert-danger " role="alert">
                {{massege}}
            </div>
            {% elif check_s == 0 %}
                <div class="alert alert-success " role="alert">
                    {{massege}}
                </div>
            {% endif %}

        {% endif %}
        <table  class="table table-hover">
        <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">อุปกรณ์ที่</th>
            <th scope="col">จำนวนที่ยืม</th>
            <th scope="col">วันที่ยืม</th>
            <th scope="col">วันที่คืน</th>
            <th scope="col">ลบ</th>
            </tr>
        </thead>
        <tbody>
        <script> 
            var i = 1
        </script>
        {% for data in datas %}
            <tr>
            <th scope="row"><script>document.write(i);</script></th>
            <td>{{data.Eqm_name.Eqm_name}}</td>
            <td>
                <form action="{% url 'myapp:Update_amount' user.username %}" method="post">
                    {% csrf_token %}
                    <input type="hidden"  name="ID" value="{{data.id}}">
                    <input class = "style_231" type="text"  name="update_mount" value="{{data.Get_Amount}}">
                    <input class="button2" type="submit" value="Update">
                </form> 
            </td>
            <td>{{data.date_br}}</td>
            <td>{{data.Date_repatriate}}</td>
            <td>
                <form action="{% url 'myapp:Delete' user.username %}" method="post">
                    {% csrf_token %}
                    <input type="hidden"  name="ID" value="{{data.id}}">
                    <input class="button2" type="submit" value="ลบ">
                </form> 
            </td>
            </tr>
        <script>i++;</script>
        {% endfor %}
        </tbody>
        </table>
        <center><h2>{{massage}}</h2></center>
    </div>
   
    <form action="{% url 'myapp:insert_borrow' %}" method="post">
         {% csrf_token %}
        <input type="hidden"  name="username" value="{{user.username}}">
        <center><input class="button3" type="submit" value="ยืนยันการยืมทั้งหมด"></center>
    </form> 
{% endblock %}